### ISSUE TITLE
classic.bibliography.author.birth has nonsense years

### ISSUE THREAD

**Issue by acbart** [RealTimeWeb/datasets#20]
Somehow, some of the years are not in the 0-2000 range. I think at least one person is listed as being born in 12,000 AD.

**Comment by RyanWhitcomb-VT** [comment]
So I went back and double checked my work today, but I did not find any births that were over 2000 years.  All the birth dates aren't necessarily between 0-2000 though because some authors, like Aristotle, were born before 0 AD

**Comment by acbart** [comment]
I'll have to double check that I've pulled recently; might be working on
old data.

On Mon, Jun 6, 2016 at 10:52 AM, Ryan Whitcomb <notifications@github.com>
wrote:

> So I went back and double checked my work today, but I did not find any
> births that were over 2000 years. All the birth dates aren't necessarily
> between 0-2000 though because some authors, like Aristotle, were born
> before 0 AD
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RealTimeWeb/datasets/issues/20#issuecomment-223983073>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2wy6xdEc6Yh-nKz9KDcitUsSJ8LdWSks5qJDQ9gaJpZM4IpS1B>
> .
>



-- 
Austin Cory Bart
Computer Science PhD student at Virginia Tech
http://www.acbart.com
