### ISSUE TITLE
Rural population / urban population in global development

### ISSUE THREAD

**Issue by acbart** [RealTimeWeb/datasets#84]
One is an absolute value, one is a percent. Documentation says they are both percents. Check out Canada for an example.

**Comment by RyanWhitcomb-VT** [comment]
Rural is value,  urban is percent.  Changed key and comment to reflect this.

**Comment by acbart** [comment]
We'll see if this is sufficient. We might want to have one or the other, or possibly both for redundancy. But for now, let's just close it.
